#!/bin/bash
# Ül1: arvuta vahemikus 1..10 (kaasaarvatud) paarisarvude summa.

sum=0
for i in {1..10}; do
  if (( i % 2 == 0 )); then
    (( sum += i ))
  fi
done
echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $sum"
