#!/bin/bash
# Eesmärk: kontrolli käsurea argumendina antud täisarvu paarsust.

# Täpselt 1 argument
if [ "$#" -ne 1 ]; then
  echo "Käivita see skript koos arvuga, mille paarsust soovid kontrollida. Näiteks: ./paarsus 3"
  exit 1
fi

arv="$1"

# Kontrolli, et oleks täisarv (lubame miinusmärgi)
if ! [[ "$arv" =~ ^-?[0-9]+$ ]]; then
  echo "Viga: palun esita täisarv. Näide: ./paarsus -4"
  exit 1
fi

if (( arv % 2 == 0 )); then
  echo "Antud arv on paaris"
else
  echo "Antud arv on paaritu"
fi
